### get /
GET http://localhost:5003

### register a user POST/AUTH/REGISTER
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username":"vv@gmail.com",
    "password":"123123"
}


### login a user POST/AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username":"vv@gmail.com",
    "password":"123123"
}

### fetch all todos GET/TODOS (protected)
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ5NjQ5OTY0LCJleHAiOjE3NDk3MzYzNjR9.0B15mpVSz_2F_hglY-6_adIQJLCosVUy1dN8nxhCVes

### Creates a new todo POST /TODOS (protected) 
POST http://localhost:5003/todos 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ5NjQ5OTY0LCJleHAiOjE3NDk3MzYzNjR9.0B15mpVSz_2F_hglY-6_adIQJLCosVUy1dN8nxhCVes
Content-Type: application/json

{
"task": "Finish coding the projects"
}

### Update a todo PUT /TODOS/:ID (protected) 
PUT http://localhost:5003/todos/2?page=4 
Authorization:   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ5NjQ5OTY0LCJleHAiOjE3NDk3MzYzNjR9.0B15mpVSz_2F_hglY-6_adIQJLCosVUy1dN8nxhCVes
Content-Type: application/json

{
"completed": 1
}

### Delete a todo DELETE /TODOS/:ID (protected) 
DELETE http://localhost:5003/todos/2 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ5NjQ5OTY0LCJleHAiOjE3NDk3MzYzNjR9.0B15mpVSz_2F_hglY-6_adIQJLCosVUy1dN8nxhCVes